#pragma once

#include "gserializer/enum.h"

namespace gcore
{
    enum class keyboard_key
    {
        first,
        space = first,
        apostrophe,
        comma,
        minus,
        period,
        slash,
        key_0,
        key_1,
        key_2,
        key_3,
        key_4,
        key_5,
        key_6,
        key_7,
        key_8,
        key_9,
        semicolon,
        equal,
        a,
        b,
        c,
        d,
        e,
        f,
        g,
        h,
        i,
        j,
        k,
        l,
        m,
        n,
        o,
        p,
        q,
        r,
        s,
        t,
        u,
        v,
        w,
        x,
        y,
        z,
        left_bracket,
        backslash,
        right_bracket,
        grave_accent,
        world_1,
        world_2,
        escape,
        enter,
        tab,
        backspace,
        insert,
        delete_key,
        right,
        left,
        down,
        up,
        page_up,
        page_down,
        home,
        end,
        caps_lock,
        scroll_lock,
        num_lock,
        print_screen,
        pause,
        f1,
        f2,
        f3,
        f4,
        f5,
        f6,
        f7,
        f8,
        f9,
        f10,
        f11,
        f12,
        f13,
        f14,
        f15,
        f16,
        f17,
        f18,
        f19,
        f20,
        f21,
        f22,
        f23,
        f24,
        f25,
        kp_0,
        kp_1,
        kp_2,
        kp_3,
        kp_4,
        kp_5,
        kp_6,
        kp_7,
        kp_8,
        kp_9,
        kp_decimal,
        kp_divide,
        kp_multiply,
        kp_subtract,
        kp_add,
        kp_enter,
        kp_equal,
        left_shift,
        left_control,
        left_alt,
        left_super,
        right_shift,
        right_control,
        right_alt,
        right_super,
        menu,
        count,
    };
    
    enum class mouse_key
    {
        first,
        button_1 = first,
        button_2,
        button_3,
        button_4,
        button_5,
        button_6,
        button_7,
        button_8,
        count,
    };
    
    
    enum class key_state
    {
        released,
        pressed,
    };

    GSERIALIZER_FORWARD_DECLARE_ENUM_SERIALIZATION(gcore::keyboard_key);
    GSERIALIZER_FORWARD_DECLARE_ENUM_SERIALIZATION(gcore::mouse_key);
    GSERIALIZER_FORWARD_DECLARE_ENUM_SERIALIZATION(gcore::key_state);
}


